### ISSUE TITLE
rsr not compatible with pandas 2.0

### ISSUE THREAD

**Issue by gregoryng** [cgrima/rsr#2]
FYI, 

pandas removes the append function in 2.0, which causes some problems for the RSR code.  

```
Traceback (most recent call last):
  File "/home/***/***/data/202308_rsr/./test_incircles.py", line 26, in <module>
    out = rsr.run.incircles(data2['surf_amp'], data2['SUB_SC_EAST_LONGITUDE'],
  File "rsr/rsr/run.py", line 308, in incircles
    results = results.append(b, ignore_index=True)
  File "/home/***/***/data/202308_rsr/ve_rsr1/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append

When running with pandas 1.5, this warning is given:

```
rsr/rsr/run.py:308: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```

**Comment by gregoryng** [comment]
@cgrima, I guess FYI, I am going to do some work on rsr and I might have a pull request soon, so I think no need for you to work on this right now.

**Comment by cgrima** [comment]
Gotcha, thanks!

**Comment by gregoryng** [comment]
Merged into master with https://github.com/cgrima/rsr/pull/3
